import { useEffect, useState } from 'react'
const THEME_ART='/assets/branding/the-outpouring.png'
const LOGO='/assets/branding/glory-conference-logo.png'
const ministers=[
 ['HOST','PROPHET JOSHUA OHANYE','/assets/ministers/joshua-ohanye.jpeg'],
 ['MUSIC MINISTER','CHINYERE UDOMA','/assets/ministers/chinyere-udoma.PNG'],
 ['MUSIC MINISTER','REV. CHRIS OKOLO','/assets/ministers/chris-okolo.png']
]
const nav=[['ABOUT','/about'],['MINISTERS','/ministers'],['PRAYER GUIDE','/prayer-guide'],['SCHEDULE','/schedule'],['TESTIMONIES','/testimonies'],['GIVE','/giving']]
function ThemeArtwork({className=''}){const[failed,setFailed]=useState(false);if(failed)return <h1 className={'theme-fallback '+className}><span>THE</span> OUTPOURING</h1>;return <img className={'theme-art '+className} src={THEME_ART} alt="The Outpouring" onError={()=>setFailed(true)}/>}
function Header(){const[scrolled,setScrolled]=useState(false),[open,setOpen]=useState(false);useEffect(()=>{const f=()=>setScrolled(scrollY>30);f();addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);return <header className={scrolled?'nav nav-scrolled':'nav'}><a className="brand" href="/"><img className="brand-logo" src={LOGO} alt="Glory Conference 2026"/></a><nav className={open?'nav-links open':'nav-links'}>{nav.map(([n,u])=><a key={u} href={u}>{n}</a>)}</nav><a className="nav-cta" href="/register">REGISTER</a><button className="menu-button" aria-label="Toggle menu" onClick={()=>setOpen(!open)}><span/><span/></button></header>}
function Footer(){return <footer><a href="/"><img className="footer-logo" src={LOGO} alt="Glory Conference 2026"/></a><span>THE OUTPOURING · JOEL 2:28</span><span>NSUKKA · NIGERIA</span></footer>}
function Shell({eyebrow,title,children}){return <main><Header/><section className="page-hero"><div className="rain"/><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>GLORY CONFERENCE 2026 · THE OUTPOURING</p></section>{children}<Footer/></main>}
function Home(){return <main><section className="hero"><div className="rain"/><div className="hero-glow"/><Header/><div className="hero-content"><p className="eyebrow">GLORY CONFERENCE 2026 PRESENTS</p><ThemeArtwork className="hero-theme"/><p className="scripture">“And it shall come to pass afterward, that I will pour out my spirit upon all flesh...” <b>JOEL 2:28</b></p><p className="date">NOVEMBER 12 — 14, 2026 · NSUKKA</p><div className="actions"><a className="button primary" href="/register">REGISTER NOW →</a><a className="button ghost" href="/prayer-guide">21-DAY PRAYER GUIDE</a></div></div></section><section className="section-dark center feature"><p className="eyebrow">3 DAYS OF HIS PRESENCE</p><ThemeArtwork className="feature-theme"/><p>Three days set apart for worship, the Word, encounters and the transforming work of the Holy Spirit.</p><div className="home-links"><a href="/about">ABOUT THE CONFERENCE →</a><a href="/ministers">MEET THE MINISTERS →</a><a href="/schedule">VIEW SCHEDULE →</a></div></section><section className="home-ministers"><div className="home-ministers-heading"><div><p className="eyebrow">GLORY CONFERENCE 2026</p><h2>MINISTERING</h2></div><a href="/ministers">VIEW ALL →</a></div><MinisterCards/></section><section className="home-prayer"><p className="eyebrow">PREPARE YOUR HEART</p><h2>21 DAYS TO<br/>THE OUTPOURING</h2><p>Join the Pre-Glory Conference Fast & Prayer as we prepare our hearts for November.</p><a className="button primary" href="/prayer-guide">ENTER PRAYER GUIDE →</a></section><section className="home-give"><div><p className="eyebrow dark">PARTNER WITH THE VISION</p><h2>GIVE TOWARDS<br/>THE OUTPOURING</h2></div><a className="button primary" href="/giving">VISIT GIVING PAGE →</a></section><Footer/></main>}
function MinisterCards(){return <div className="minister-grid">{ministers.map(([role,name,image],i)=><article className="minister-card" key={name}><div className={'portrait portrait-'+(i+1)}><img src={image} alt={name}/></div><div className="minister-info"><span>{role}</span><h3>{name}</h3></div></article>)}</div>}
function About(){return <Shell eyebrow="THE GATHERING" title="ABOUT"><section className="page-light split"><h2>WHAT IS<br/>GLORY CONFERENCE?</h2><div><p>Glory Conference is a gathering centered on the presence of God, the Word and the transforming work of the Holy Spirit.</p><p>In 2026, we gather under one prophetic theme: <strong>The Outpouring.</strong></p><blockquote>“I will pour out my spirit upon all flesh...”<br/><b>JOEL 2:28</b></blockquote></div></section></Shell>}
function Ministers(){return <Shell eyebrow="VOICES OF THE CONFERENCE" title="MINISTERING"><section className="page-dark"><MinisterCards/></section></Shell>}
function PrayerGuide(){return <Shell eyebrow="PRE-GLORY CONFERENCE FAST" title="21-DAY PRAYER GUIDE"><section className="page-light"><div className="page-copy"><h2>PREPARE<br/>YOUR HEART.</h2><p>Twenty-one days of consecration, prayer and expectation leading into Glory Conference 2026. Official prayer focuses will be published here daily.</p></div><div className="prayer-grid">{Array.from({length:21},(_,i)=><article className="prayer-card upcoming" key={i}><span>DAY {String(i+1).padStart(2,'0')}</span><h3>PRAYER FOCUS COMING SOON</h3><small>DAILY PRAYER</small><i>COMING SOON</i></article>)}</div></section></Shell>}
function Schedule(){return <Shell eyebrow="NOVEMBER 12 — 14, 2026" title="SCHEDULE"><section className="page-dark schedule-page"><div><h2>NSUKKA</h2><p>NO. 4 UWANI UGWU STREET<br/>OFF IKENGA JUNCTION, NSUKKA.</p></div><div className="session-list">{[['THU · NOV 12','OPENING NIGHT','4:00 PM'],['FRI · NOV 13','OUTPOURING NIGHT','4:00 PM'],['SAT · NOV 14','GRAND FINALE','9:00 AM']].map(([day,title,time])=><article className="session" key={day}><div><span>{day}</span><h3>{title}</h3></div><strong>{time}</strong></article>)}</div></section></Shell>}
function Testimonies(){return <Shell eyebrow="STORIES OF ENCOUNTER" title="TESTIMONIES"><section className="page-light"><div className="page-copy"><h2>WHAT GOD<br/>HAS DONE.</h2><p>Official testimonies from previous Glory Conferences will be published here as they are supplied.</p></div></section></Shell>}
function Giving(){return <Shell eyebrow="PARTNER WITH THE VISION" title="GIVING"><section className="page-light split"><h2>GIVE TOWARDS<br/>THE OUTPOURING.</h2><div><p>This dedicated page is reserved for Glory Conference 2026 partnership information.</p><div className="notice-box"><span>OFFICIAL GIVING INFORMATION</span><strong>COMING SOON</strong></div></div></section></Shell>}
function Register(){return <Shell eyebrow="NOVEMBER 12 — 14 · NSUKKA" title="REGISTER"><section className="page-light center register-page"><h2>GLORY CONFERENCE<br/>2026</h2><p>Registration details will be announced soon.</p><p>Enquiries: <strong>+234 703 640 3016</strong></p></section></Shell>}
export default function App(){const path=location.pathname.replace(/\/$/,'')||'/';const pages={'/':Home,'/about':About,'/ministers':Ministers,'/prayer-guide':PrayerGuide,'/schedule':Schedule,'/testimonies':Testimonies,'/giving':Giving,'/give':Giving,'/register':Register};const Page=pages[path]||Home;return <Page/>}
