import { useEffect, useState } from 'react'
import './special-pages.css'
import { Header, Footer } from './App.jsx'

const LOGO='/assets/branding/glory-conference-logo.png'
const THEME='/assets/branding/the-outpouring.png'
const nav=[['ABOUT','/about'],['MINISTERS','/ministers'],['PRAYER GUIDE','/prayer-guide'],['SCHEDULE','/schedule'],['TESTIMONIES','/testimonies'],['MERCH','/merch'],['GIVE','/giving']]

function SpecialHeader({scrollAway=false}){const[scrolled,setScrolled]=useState(false),[open,setOpen]=useState(false);useEffect(()=>{const f=()=>setScrolled(scrollY>30);f();addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);return <header className={`${scrolled?'nav nav-scrolled':'nav'}${scrollAway?' pastors-scroll-header':''}`}><a className="brand" href="/"><img className="brand-logo" src={LOGO} alt="Glory Conference 2026"/></a><nav className={open?'nav-links open':'nav-links'}>{nav.map(([n,u])=><a key={u} href={u}>{n}</a>)}</nav><a className="nav-cta" href="/register">REGISTER</a><button className="menu-button" aria-label="Toggle menu" onClick={()=>setOpen(!open)}><span/><span/></button></header>}
function SpecialFooter(){return <footer className="sp-footer"><img src={THEME} alt="The Outpouring"/><div className="sp-footer-links"><a href="/">HOME</a><a href="/pastors-ministers">PASTORS & MINISTERS</a><a href="/volunteer">VOLUNTEER</a><a href="/giving">GIVE</a><a href="/register">REGISTER</a></div><p>NOVEMBER 12–14, 2026 · NSUKKA, NIGERIA · +234 703 640 3016</p><small>© 2026 GLORY CONFERENCE. ALL RIGHTS RESERVED.</small></footer>}
function PageHero({eyebrow,title,copy}){return <section className="page-hero sp-native-hero"><div className="rain"/><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="sp-hero-copy">{copy}</p></section>}
function WhatsAppForm({type}){const pastor=type==='minister';const[name,setName]=useState(''),[phone,setPhone]=useState(''),[church,setChurch]=useState(''),[detail,setDetail]=useState('');function submit(e){e.preventDefault();const intro=pastor?'Glory Conference 2026 Pastors & Ministers Interest':'Glory Conference 2026 Volunteer Interest';const lines=[intro,`Name: ${name}`,`Phone: ${phone}`,pastor?`Church / Ministry: ${church}`:`Church / Organisation: ${church}`,pastor?`Ministry role: ${detail}`:`Area I serve in / would like to help with: ${detail}`];window.location.href=`https://wa.me/2347036403016?text=${encodeURIComponent(lines.join('\n'))}`}return <form className="sp-form" onSubmit={submit}><label>FULL NAME<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label><label>PHONE NUMBER<input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Your phone number"/></label><label>{pastor?'CHURCH / MINISTRY':'CHURCH / ORGANISATION'}<input required value={church} onChange={e=>setChurch(e.target.value)} placeholder={pastor?'Church or ministry name':'Church or organisation'}/></label><label>{pastor?'MINISTRY ROLE':'HOW WOULD YOU LIKE TO SERVE?'}<textarea required value={detail} onChange={e=>setDetail(e.target.value)} placeholder={pastor?'Pastor, Gospel minister, ministry leader…':'Tell us briefly where you can help or what you do well.'}/></label><button type="submit">SEND INTEREST →</button><small>This opens WhatsApp with your details ready to send to the Glory Conference enquiry line.</small></form>}
export function PastorsMinisters(){return <main className="sp-page"><Header/><PageHero eyebrow="GLORY CONFERENCE 2026" title="PASTORS & MINISTERS" copy="GLORY CONFERENCE 2026 · THE OUTPOURING"/><section className="sp-intro"><div><p className="sp-eyebrow">A WORD OF WELCOME</p><h2>WE LOOK FORWARD<br/>TO RECEIVING YOU.</h2></div><div><p>Glory Conference welcomes pastors, Gospel ministers and ministry leaders who will be joining the gathering in Nsukka from November 12–14, 2026.</p><p>This page is separate from our <a href="/ministers">ministering guests</a> page. It is for ministers attending the conference and for official communication relevant to their participation.</p></div></section><section className="sp-info"><article><span>01</span><h3>CONFERENCE DATES</h3><p>Thursday, November 12 and Friday, November 13 at 4PM. Saturday, November 14 at 9AM.</p></article><article><span>02</span><h3>VENUE</h3><p>No. 4 Uwani Ugwu Street, Off Ikenga Junction, Nsukka.</p></article><article><span>03</span><h3>MINISTER INFORMATION</h3><p>Any additional arrangements specifically confirmed for attending pastors and ministers will be published here once available.</p></article></section><section className="sp-interest"><div><p className="sp-eyebrow">PASTORS & MINISTERS</p><h2>LET US KNOW<br/>YOU'RE COMING.</h2><p>Send your details to the conference team so your interest is on record. This does not promise accommodation, reserved seating or travel support.</p></div><WhatsAppForm type="minister"/></section><Footer/></main>}
export function Volunteer(){return <main className="sp-page"><Header/><PageHero eyebrow="SERVE AT GLORY CONFERENCE 2026" title="VOLUNTEER" copy="GLORY CONFERENCE 2026 · THE OUTPOURING"/><section className="sp-intro"><div><p className="sp-eyebrow">VOLUNTEER</p><h2>SERVE THE VISION.<br/>SERVE THE PEOPLE.</h2></div><div><p>Volunteering is an opportunity to contribute your time, skill and strength to the work behind Glory Conference 2026.</p><p>Whether you already serve in a church team or simply want to make yourself available, send your interest below. The conference team will communicate confirmed roles and instructions directly.</p></div></section><section className="sp-info"><article><span>01</span><h3>AVAILABILITY</h3><p>Be ready to communicate clearly about when you can serve during the November 12–14 conference period.</p></article><article><span>02</span><h3>WILLINGNESS</h3><p>Come prepared to support the conference where your abilities are useful and where the team confirms a need.</p></article><article><span>03</span><h3>EXCELLENCE</h3><p>We value service that is responsible, respectful, attentive and centered on helping people encounter God without distraction.</p></article></section><section className="sp-interest"><div><p className="sp-eyebrow">VOLUNTEER INTEREST</p><h2>MAKE YOURSELF<br/>AVAILABLE.</h2><p>Tell us briefly who you are and how you can help. Submitting interest does not automatically assign a role; the conference team will follow up with confirmed information.</p></div><WhatsAppForm type="volunteer"/></section><Footer/></main>}
export function SpecialPage(){const path=location.pathname.replace(/\/$/,'')||'/';if(path==='/pastors-ministers')return <PastorsMinisters/>;if(path==='/volunteer')return <Volunteer/>;return null}
